services:
  api_server:
    container_name: api_server
    image: api_server:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_URI: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
    ports:
      - 3000:3000
    volumes:
      - api_server_data:/var/lib/api_server/data
    networks:
      - backend

volumes:
  api_server_data:

networks:
  backend: